#############################################################################
# Makefile for building: ServerGeomarketing
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  ServerGeomarketing.pro
# Template: app
# Command: /home/salvatore/Qt-Static/bin/qmake -config release -o Makefile ServerGeomarketing.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../Qt-Static/mkspecs/linux-g++ -I. -I../../Qt-Static/include -I../../Qt-Static/include/QtSql -I../../Qt-Static/include/QtNetwork -I../../Qt-Static/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/home/salvatore/Qt-Static/lib -L/home/salvatore/Qt-Static/plugins/sqldrivers -lqsqlite -lQt5Sql -L/home/salvatore/Qt-Static/plugins/bearer -lqgenericbearer -lQt5Network -lQt5Core -lz -lm -ldl -lrt -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/salvatore/Qt-Static/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		myserver.cpp \
		mythread.cpp \
		servergeomarketing_plugin_import.cpp moc_myserver.cpp \
		moc_mythread.cpp
OBJECTS       = main.o \
		myserver.o \
		mythread.o \
		servergeomarketing_plugin_import.o \
		moc_myserver.o \
		moc_mythread.o
DIST          = ../../Qt-Static/mkspecs/features/spec_pre.prf \
		../../Qt-Static/mkspecs/common/shell-unix.conf \
		../../Qt-Static/mkspecs/common/unix.conf \
		../../Qt-Static/mkspecs/common/linux.conf \
		../../Qt-Static/mkspecs/common/gcc-base.conf \
		../../Qt-Static/mkspecs/common/gcc-base-unix.conf \
		../../Qt-Static/mkspecs/common/g++-base.conf \
		../../Qt-Static/mkspecs/common/g++-unix.conf \
		../../Qt-Static/mkspecs/qconfig.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_core.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_designer.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_gui.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_help.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_network.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qml.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quick.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_script.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sql.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_svg.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xml.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qdds.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qdeclarativeview.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qjp2.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmng.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_counterplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_dummy.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qxcb.pri \
		../../Qt-Static/mkspecs/features/qt_functions.prf \
		../../Qt-Static/mkspecs/features/qt_config.prf \
		../../Qt-Static/mkspecs/linux-g++/qmake.conf \
		../../Qt-Static/mkspecs/features/spec_post.prf \
		../../Qt-Static/mkspecs/features/exclusive_builds.prf \
		../../Qt-Static/mkspecs/features/default_pre.prf \
		../../Qt-Static/mkspecs/features/resolve_config.prf \
		../../Qt-Static/mkspecs/features/default_post.prf \
		../../Qt-Static/mkspecs/features/warn_on.prf \
		../../Qt-Static/mkspecs/features/qt.prf \
		../../Qt-Static/mkspecs/features/resources.prf \
		../../Qt-Static/mkspecs/features/moc.prf \
		../../Qt-Static/mkspecs/features/unix/thread.prf \
		../../Qt-Static/mkspecs/features/testcase_targets.prf \
		../../Qt-Static/mkspecs/features/exceptions.prf \
		../../Qt-Static/mkspecs/features/yacc.prf \
		../../Qt-Static/mkspecs/features/lex.prf \
		ServerGeomarketing.pro main.cpp \
		myserver.cpp \
		mythread.cpp \
		servergeomarketing_plugin_import.cpp
QMAKE_TARGET  = ServerGeomarketing
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ServerGeomarketing


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): /home/salvatore/Qt-Static/lib/libQt5Sql.a /home/salvatore/Qt-Static/lib/libQt5Network.a /home/salvatore/Qt-Static/lib/libQt5Core.a $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ServerGeomarketing.pro ../../Qt-Static/mkspecs/linux-g++/qmake.conf ../../Qt-Static/mkspecs/features/spec_pre.prf \
		../../Qt-Static/mkspecs/common/shell-unix.conf \
		../../Qt-Static/mkspecs/common/unix.conf \
		../../Qt-Static/mkspecs/common/linux.conf \
		../../Qt-Static/mkspecs/common/gcc-base.conf \
		../../Qt-Static/mkspecs/common/gcc-base-unix.conf \
		../../Qt-Static/mkspecs/common/g++-base.conf \
		../../Qt-Static/mkspecs/common/g++-unix.conf \
		../../Qt-Static/mkspecs/qconfig.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_core.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_designer.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_gui.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_help.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_network.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qml.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quick.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_script.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sql.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_svg.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_x11extras.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xml.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt-Static/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qdds.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qdeclarativeview.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qjp2.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qlinuxfb.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qmng.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtaccessiblequick.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_counterplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_dummy.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt-Static/mkspecs/modules/qt_plugin_qxcb.pri \
		../../Qt-Static/mkspecs/features/qt_functions.prf \
		../../Qt-Static/mkspecs/features/qt_config.prf \
		../../Qt-Static/mkspecs/linux-g++/qmake.conf \
		../../Qt-Static/mkspecs/features/spec_post.prf \
		../../Qt-Static/mkspecs/features/exclusive_builds.prf \
		../../Qt-Static/mkspecs/features/default_pre.prf \
		../../Qt-Static/mkspecs/features/resolve_config.prf \
		../../Qt-Static/mkspecs/features/default_post.prf \
		../../Qt-Static/mkspecs/features/warn_on.prf \
		../../Qt-Static/mkspecs/features/qt.prf \
		../../Qt-Static/mkspecs/features/resources.prf \
		../../Qt-Static/mkspecs/features/moc.prf \
		../../Qt-Static/mkspecs/features/unix/thread.prf \
		../../Qt-Static/mkspecs/features/testcase_targets.prf \
		../../Qt-Static/mkspecs/features/exceptions.prf \
		../../Qt-Static/mkspecs/features/yacc.prf \
		../../Qt-Static/mkspecs/features/lex.prf \
		ServerGeomarketing.pro \
		/home/salvatore/Qt-Static/lib/libQt5Sql.prl \
		/home/salvatore/Qt-Static/lib/libQt5Core.prl \
		/home/salvatore/Qt-Static/lib/libQt5Network.prl \
		/home/salvatore/Qt-Static/plugins/sqldrivers/libqsqlite.prl \
		/home/salvatore/Qt-Static/plugins/bearer/libqgenericbearer.prl
	$(QMAKE) -config release -o Makefile ServerGeomarketing.pro
../../Qt-Static/mkspecs/features/spec_pre.prf:
../../Qt-Static/mkspecs/common/shell-unix.conf:
../../Qt-Static/mkspecs/common/unix.conf:
../../Qt-Static/mkspecs/common/linux.conf:
../../Qt-Static/mkspecs/common/gcc-base.conf:
../../Qt-Static/mkspecs/common/gcc-base-unix.conf:
../../Qt-Static/mkspecs/common/g++-base.conf:
../../Qt-Static/mkspecs/common/g++-unix.conf:
../../Qt-Static/mkspecs/qconfig.pri:
../../Qt-Static/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt-Static/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt-Static/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_core.pri:
../../Qt-Static/mkspecs/modules/qt_lib_core_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_declarative.pri:
../../Qt-Static/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_designer.pri:
../../Qt-Static/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_gui.pri:
../../Qt-Static/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_help.pri:
../../Qt-Static/mkspecs/modules/qt_lib_help_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt-Static/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt-Static/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_network.pri:
../../Qt-Static/mkspecs/modules/qt_lib_network_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_nfc.pri:
../../Qt-Static/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_opengl.pri:
../../Qt-Static/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt-Static/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_positioning.pri:
../../Qt-Static/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt-Static/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_qml.pri:
../../Qt-Static/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt-Static/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_quick.pri:
../../Qt-Static/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt-Static/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_script.pri:
../../Qt-Static/mkspecs/modules/qt_lib_script_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt-Static/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_sensors.pri:
../../Qt-Static/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_serialport.pri:
../../Qt-Static/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_sql.pri:
../../Qt-Static/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_svg.pri:
../../Qt-Static/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_testlib.pri:
../../Qt-Static/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_uitools.pri:
../../Qt-Static/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_websockets.pri:
../../Qt-Static/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_widgets.pri:
../../Qt-Static/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_x11extras.pri:
../../Qt-Static/mkspecs/modules/qt_lib_x11extras_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_xml.pri:
../../Qt-Static/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt-Static/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt-Static/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_composeplatforminputcontextplugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qdds.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qdeclarativeview.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qevdevkeyboardplugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qevdevmouseplugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qevdevtabletplugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qevdevtouchplugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qicns.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qico.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qjp2.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qlinuxfb.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qminimal.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_qtquick2.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qmldbg_tcp_qtdeclarative.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qmng.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qsqlite.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qsvg.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtaccessiblequick.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtaccessiblewidgets.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtga.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtiff.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_counterplugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_dummy.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qtsensors_linuxsys.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qwbmp.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qwebp.pri:
../../Qt-Static/mkspecs/modules/qt_plugin_qxcb.pri:
../../Qt-Static/mkspecs/features/qt_functions.prf:
../../Qt-Static/mkspecs/features/qt_config.prf:
../../Qt-Static/mkspecs/linux-g++/qmake.conf:
../../Qt-Static/mkspecs/features/spec_post.prf:
../../Qt-Static/mkspecs/features/exclusive_builds.prf:
../../Qt-Static/mkspecs/features/default_pre.prf:
../../Qt-Static/mkspecs/features/resolve_config.prf:
../../Qt-Static/mkspecs/features/default_post.prf:
../../Qt-Static/mkspecs/features/warn_on.prf:
../../Qt-Static/mkspecs/features/qt.prf:
../../Qt-Static/mkspecs/features/resources.prf:
../../Qt-Static/mkspecs/features/moc.prf:
../../Qt-Static/mkspecs/features/unix/thread.prf:
../../Qt-Static/mkspecs/features/testcase_targets.prf:
../../Qt-Static/mkspecs/features/exceptions.prf:
../../Qt-Static/mkspecs/features/yacc.prf:
../../Qt-Static/mkspecs/features/lex.prf:
ServerGeomarketing.pro:
/home/salvatore/Qt-Static/lib/libQt5Sql.prl:
/home/salvatore/Qt-Static/lib/libQt5Core.prl:
/home/salvatore/Qt-Static/lib/libQt5Network.prl:
/home/salvatore/Qt-Static/plugins/sqldrivers/libqsqlite.prl:
/home/salvatore/Qt-Static/plugins/bearer/libqgenericbearer.prl:
qmake: FORCE
	@$(QMAKE) -config release -o Makefile ServerGeomarketing.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/ServerGeomarketing1.0.0 || mkdir -p .tmp/ServerGeomarketing1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/ServerGeomarketing1.0.0/ && $(COPY_FILE) --parents myserver.h mythread.h .tmp/ServerGeomarketing1.0.0/ && $(COPY_FILE) --parents main.cpp myserver.cpp mythread.cpp servergeomarketing_plugin_import.cpp .tmp/ServerGeomarketing1.0.0/ && (cd `dirname .tmp/ServerGeomarketing1.0.0` && $(TAR) ServerGeomarketing1.0.0.tar ServerGeomarketing1.0.0 && $(COMPRESS) ServerGeomarketing1.0.0.tar) && $(MOVE) `dirname .tmp/ServerGeomarketing1.0.0`/ServerGeomarketing1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ServerGeomarketing1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) /home/salvatore/Qt-workspace/ServerGeomarketing/servergeomarketing_plugin_import.cpp
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_myserver.cpp moc_mythread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_myserver.cpp moc_mythread.cpp
moc_myserver.cpp: ../../Qt-Static/include/QtNetwork/QTcpServer \
		../../Qt-Static/include/QtNetwork/qtcpserver.h \
		../../Qt-Static/include/QtCore/qobject.h \
		../../Qt-Static/include/QtCore/qobjectdefs.h \
		../../Qt-Static/include/QtCore/qnamespace.h \
		../../Qt-Static/include/QtCore/qglobal.h \
		../../Qt-Static/include/QtCore/qconfig.h \
		../../Qt-Static/include/QtCore/qfeatures.h \
		../../Qt-Static/include/QtCore/qsystemdetection.h \
		../../Qt-Static/include/QtCore/qprocessordetection.h \
		../../Qt-Static/include/QtCore/qcompilerdetection.h \
		../../Qt-Static/include/QtCore/qtypeinfo.h \
		../../Qt-Static/include/QtCore/qtypetraits.h \
		../../Qt-Static/include/QtCore/qsysinfo.h \
		../../Qt-Static/include/QtCore/qlogging.h \
		../../Qt-Static/include/QtCore/qflags.h \
		../../Qt-Static/include/QtCore/qatomic.h \
		../../Qt-Static/include/QtCore/qbasicatomic.h \
		../../Qt-Static/include/QtCore/qatomic_bootstrap.h \
		../../Qt-Static/include/QtCore/qgenericatomic.h \
		../../Qt-Static/include/QtCore/qatomic_msvc.h \
		../../Qt-Static/include/QtCore/qatomic_armv7.h \
		../../Qt-Static/include/QtCore/qatomic_armv6.h \
		../../Qt-Static/include/QtCore/qatomic_armv5.h \
		../../Qt-Static/include/QtCore/qatomic_ia64.h \
		../../Qt-Static/include/QtCore/qatomic_mips.h \
		../../Qt-Static/include/QtCore/qatomic_x86.h \
		../../Qt-Static/include/QtCore/qatomic_cxx11.h \
		../../Qt-Static/include/QtCore/qatomic_gcc.h \
		../../Qt-Static/include/QtCore/qatomic_unix.h \
		../../Qt-Static/include/QtCore/qglobalstatic.h \
		../../Qt-Static/include/QtCore/qmutex.h \
		../../Qt-Static/include/QtCore/qnumeric.h \
		../../Qt-Static/include/QtCore/qobjectdefs_impl.h \
		../../Qt-Static/include/QtCore/qstring.h \
		../../Qt-Static/include/QtCore/qchar.h \
		../../Qt-Static/include/QtCore/qbytearray.h \
		../../Qt-Static/include/QtCore/qrefcount.h \
		../../Qt-Static/include/QtCore/qarraydata.h \
		../../Qt-Static/include/QtCore/qstringbuilder.h \
		../../Qt-Static/include/QtCore/qlist.h \
		../../Qt-Static/include/QtCore/qalgorithms.h \
		../../Qt-Static/include/QtCore/qiterator.h \
		../../Qt-Static/include/QtCore/qcoreevent.h \
		../../Qt-Static/include/QtCore/qscopedpointer.h \
		../../Qt-Static/include/QtCore/qmetatype.h \
		../../Qt-Static/include/QtCore/qvarlengtharray.h \
		../../Qt-Static/include/QtCore/qcontainerfwd.h \
		../../Qt-Static/include/QtCore/qisenum.h \
		../../Qt-Static/include/QtCore/qobject_impl.h \
		../../Qt-Static/include/QtNetwork/qabstractsocket.h \
		../../Qt-Static/include/QtCore/qiodevice.h \
		../../Qt-Static/include/QtCore/qdebug.h \
		../../Qt-Static/include/QtCore/qhash.h \
		../../Qt-Static/include/QtCore/qpair.h \
		../../Qt-Static/include/QtCore/qmap.h \
		../../Qt-Static/include/QtCore/qtextstream.h \
		../../Qt-Static/include/QtCore/qlocale.h \
		../../Qt-Static/include/QtCore/qvariant.h \
		../../Qt-Static/include/QtCore/qstringlist.h \
		../../Qt-Static/include/QtCore/qdatastream.h \
		../../Qt-Static/include/QtCore/qregexp.h \
		../../Qt-Static/include/QtCore/qstringmatcher.h \
		../../Qt-Static/include/QtCore/qshareddata.h \
		../../Qt-Static/include/QtCore/qvector.h \
		../../Qt-Static/include/QtCore/qpoint.h \
		../../Qt-Static/include/QtCore/qset.h \
		../../Qt-Static/include/QtCore/qcontiguouscache.h \
		../../Qt-Static/include/QtNetwork/qhostaddress.h \
		mythread.h \
		../../Qt-Static/include/QtCore/QThread \
		../../Qt-Static/include/QtCore/qthread.h \
		../../Qt-Static/include/QtNetwork/QTcpSocket \
		../../Qt-Static/include/QtNetwork/qtcpsocket.h \
		../../Qt-Static/include/QtCore/QDebug \
		myserver.h
	/home/salvatore/Qt-Static/bin/moc $(DEFINES) -I/home/salvatore/Qt-Static/mkspecs/linux-g++ -I/home/salvatore/Qt-workspace/ServerGeomarketing -I/home/salvatore/Qt-Static/include -I/home/salvatore/Qt-Static/include/QtSql -I/home/salvatore/Qt-Static/include/QtNetwork -I/home/salvatore/Qt-Static/include/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include myserver.h -o moc_myserver.cpp

moc_mythread.cpp: ../../Qt-Static/include/QtCore/QThread \
		../../Qt-Static/include/QtCore/qthread.h \
		../../Qt-Static/include/QtCore/qobject.h \
		../../Qt-Static/include/QtCore/qobjectdefs.h \
		../../Qt-Static/include/QtCore/qnamespace.h \
		../../Qt-Static/include/QtCore/qglobal.h \
		../../Qt-Static/include/QtCore/qconfig.h \
		../../Qt-Static/include/QtCore/qfeatures.h \
		../../Qt-Static/include/QtCore/qsystemdetection.h \
		../../Qt-Static/include/QtCore/qprocessordetection.h \
		../../Qt-Static/include/QtCore/qcompilerdetection.h \
		../../Qt-Static/include/QtCore/qtypeinfo.h \
		../../Qt-Static/include/QtCore/qtypetraits.h \
		../../Qt-Static/include/QtCore/qsysinfo.h \
		../../Qt-Static/include/QtCore/qlogging.h \
		../../Qt-Static/include/QtCore/qflags.h \
		../../Qt-Static/include/QtCore/qatomic.h \
		../../Qt-Static/include/QtCore/qbasicatomic.h \
		../../Qt-Static/include/QtCore/qatomic_bootstrap.h \
		../../Qt-Static/include/QtCore/qgenericatomic.h \
		../../Qt-Static/include/QtCore/qatomic_msvc.h \
		../../Qt-Static/include/QtCore/qatomic_armv7.h \
		../../Qt-Static/include/QtCore/qatomic_armv6.h \
		../../Qt-Static/include/QtCore/qatomic_armv5.h \
		../../Qt-Static/include/QtCore/qatomic_ia64.h \
		../../Qt-Static/include/QtCore/qatomic_mips.h \
		../../Qt-Static/include/QtCore/qatomic_x86.h \
		../../Qt-Static/include/QtCore/qatomic_cxx11.h \
		../../Qt-Static/include/QtCore/qatomic_gcc.h \
		../../Qt-Static/include/QtCore/qatomic_unix.h \
		../../Qt-Static/include/QtCore/qglobalstatic.h \
		../../Qt-Static/include/QtCore/qmutex.h \
		../../Qt-Static/include/QtCore/qnumeric.h \
		../../Qt-Static/include/QtCore/qobjectdefs_impl.h \
		../../Qt-Static/include/QtCore/qstring.h \
		../../Qt-Static/include/QtCore/qchar.h \
		../../Qt-Static/include/QtCore/qbytearray.h \
		../../Qt-Static/include/QtCore/qrefcount.h \
		../../Qt-Static/include/QtCore/qarraydata.h \
		../../Qt-Static/include/QtCore/qstringbuilder.h \
		../../Qt-Static/include/QtCore/qlist.h \
		../../Qt-Static/include/QtCore/qalgorithms.h \
		../../Qt-Static/include/QtCore/qiterator.h \
		../../Qt-Static/include/QtCore/qcoreevent.h \
		../../Qt-Static/include/QtCore/qscopedpointer.h \
		../../Qt-Static/include/QtCore/qmetatype.h \
		../../Qt-Static/include/QtCore/qvarlengtharray.h \
		../../Qt-Static/include/QtCore/qcontainerfwd.h \
		../../Qt-Static/include/QtCore/qisenum.h \
		../../Qt-Static/include/QtCore/qobject_impl.h \
		../../Qt-Static/include/QtNetwork/QTcpSocket \
		../../Qt-Static/include/QtNetwork/qtcpsocket.h \
		../../Qt-Static/include/QtNetwork/qabstractsocket.h \
		../../Qt-Static/include/QtCore/qiodevice.h \
		../../Qt-Static/include/QtCore/qdebug.h \
		../../Qt-Static/include/QtCore/qhash.h \
		../../Qt-Static/include/QtCore/qpair.h \
		../../Qt-Static/include/QtCore/qmap.h \
		../../Qt-Static/include/QtCore/qtextstream.h \
		../../Qt-Static/include/QtCore/qlocale.h \
		../../Qt-Static/include/QtCore/qvariant.h \
		../../Qt-Static/include/QtCore/qstringlist.h \
		../../Qt-Static/include/QtCore/qdatastream.h \
		../../Qt-Static/include/QtCore/qregexp.h \
		../../Qt-Static/include/QtCore/qstringmatcher.h \
		../../Qt-Static/include/QtCore/qshareddata.h \
		../../Qt-Static/include/QtCore/qvector.h \
		../../Qt-Static/include/QtCore/qpoint.h \
		../../Qt-Static/include/QtCore/qset.h \
		../../Qt-Static/include/QtCore/qcontiguouscache.h \
		../../Qt-Static/include/QtCore/QDebug \
		mythread.h
	/home/salvatore/Qt-Static/bin/moc $(DEFINES) -I/home/salvatore/Qt-Static/mkspecs/linux-g++ -I/home/salvatore/Qt-workspace/ServerGeomarketing -I/home/salvatore/Qt-Static/include -I/home/salvatore/Qt-Static/include/QtSql -I/home/salvatore/Qt-Static/include/QtNetwork -I/home/salvatore/Qt-Static/include/QtCore -I/usr/include/c++/4.9 -I/usr/include/x86_64-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/4.9/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mythread.h -o moc_mythread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../Qt-Static/include/QtCore/QCoreApplication \
		../../Qt-Static/include/QtCore/qcoreapplication.h \
		../../Qt-Static/include/QtCore/qglobal.h \
		../../Qt-Static/include/QtCore/qconfig.h \
		../../Qt-Static/include/QtCore/qfeatures.h \
		../../Qt-Static/include/QtCore/qsystemdetection.h \
		../../Qt-Static/include/QtCore/qprocessordetection.h \
		../../Qt-Static/include/QtCore/qcompilerdetection.h \
		../../Qt-Static/include/QtCore/qtypeinfo.h \
		../../Qt-Static/include/QtCore/qtypetraits.h \
		../../Qt-Static/include/QtCore/qsysinfo.h \
		../../Qt-Static/include/QtCore/qlogging.h \
		../../Qt-Static/include/QtCore/qflags.h \
		../../Qt-Static/include/QtCore/qatomic.h \
		../../Qt-Static/include/QtCore/qbasicatomic.h \
		../../Qt-Static/include/QtCore/qatomic_bootstrap.h \
		../../Qt-Static/include/QtCore/qgenericatomic.h \
		../../Qt-Static/include/QtCore/qatomic_msvc.h \
		../../Qt-Static/include/QtCore/qatomic_armv7.h \
		../../Qt-Static/include/QtCore/qatomic_armv6.h \
		../../Qt-Static/include/QtCore/qatomic_armv5.h \
		../../Qt-Static/include/QtCore/qatomic_ia64.h \
		../../Qt-Static/include/QtCore/qatomic_mips.h \
		../../Qt-Static/include/QtCore/qatomic_x86.h \
		../../Qt-Static/include/QtCore/qatomic_cxx11.h \
		../../Qt-Static/include/QtCore/qatomic_gcc.h \
		../../Qt-Static/include/QtCore/qatomic_unix.h \
		../../Qt-Static/include/QtCore/qglobalstatic.h \
		../../Qt-Static/include/QtCore/qmutex.h \
		../../Qt-Static/include/QtCore/qnumeric.h \
		../../Qt-Static/include/QtCore/qstring.h \
		../../Qt-Static/include/QtCore/qchar.h \
		../../Qt-Static/include/QtCore/qbytearray.h \
		../../Qt-Static/include/QtCore/qrefcount.h \
		../../Qt-Static/include/QtCore/qnamespace.h \
		../../Qt-Static/include/QtCore/qarraydata.h \
		../../Qt-Static/include/QtCore/qstringbuilder.h \
		../../Qt-Static/include/QtCore/qobject.h \
		../../Qt-Static/include/QtCore/qobjectdefs.h \
		../../Qt-Static/include/QtCore/qobjectdefs_impl.h \
		../../Qt-Static/include/QtCore/qlist.h \
		../../Qt-Static/include/QtCore/qalgorithms.h \
		../../Qt-Static/include/QtCore/qiterator.h \
		../../Qt-Static/include/QtCore/qcoreevent.h \
		../../Qt-Static/include/QtCore/qscopedpointer.h \
		../../Qt-Static/include/QtCore/qmetatype.h \
		../../Qt-Static/include/QtCore/qvarlengtharray.h \
		../../Qt-Static/include/QtCore/qcontainerfwd.h \
		../../Qt-Static/include/QtCore/qisenum.h \
		../../Qt-Static/include/QtCore/qobject_impl.h \
		../../Qt-Static/include/QtCore/qeventloop.h \
		myserver.h \
		../../Qt-Static/include/QtNetwork/QTcpServer \
		../../Qt-Static/include/QtNetwork/qtcpserver.h \
		../../Qt-Static/include/QtNetwork/qabstractsocket.h \
		../../Qt-Static/include/QtCore/qiodevice.h \
		../../Qt-Static/include/QtCore/qdebug.h \
		../../Qt-Static/include/QtCore/qhash.h \
		../../Qt-Static/include/QtCore/qpair.h \
		../../Qt-Static/include/QtCore/qmap.h \
		../../Qt-Static/include/QtCore/qtextstream.h \
		../../Qt-Static/include/QtCore/qlocale.h \
		../../Qt-Static/include/QtCore/qvariant.h \
		../../Qt-Static/include/QtCore/qstringlist.h \
		../../Qt-Static/include/QtCore/qdatastream.h \
		../../Qt-Static/include/QtCore/qregexp.h \
		../../Qt-Static/include/QtCore/qstringmatcher.h \
		../../Qt-Static/include/QtCore/qshareddata.h \
		../../Qt-Static/include/QtCore/qvector.h \
		../../Qt-Static/include/QtCore/qpoint.h \
		../../Qt-Static/include/QtCore/qset.h \
		../../Qt-Static/include/QtCore/qcontiguouscache.h \
		../../Qt-Static/include/QtNetwork/qhostaddress.h \
		mythread.h \
		../../Qt-Static/include/QtCore/QThread \
		../../Qt-Static/include/QtCore/qthread.h \
		../../Qt-Static/include/QtNetwork/QTcpSocket \
		../../Qt-Static/include/QtNetwork/qtcpsocket.h \
		../../Qt-Static/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

myserver.o: myserver.cpp myserver.h \
		../../Qt-Static/include/QtNetwork/QTcpServer \
		../../Qt-Static/include/QtNetwork/qtcpserver.h \
		../../Qt-Static/include/QtCore/qobject.h \
		../../Qt-Static/include/QtCore/qobjectdefs.h \
		../../Qt-Static/include/QtCore/qnamespace.h \
		../../Qt-Static/include/QtCore/qglobal.h \
		../../Qt-Static/include/QtCore/qconfig.h \
		../../Qt-Static/include/QtCore/qfeatures.h \
		../../Qt-Static/include/QtCore/qsystemdetection.h \
		../../Qt-Static/include/QtCore/qprocessordetection.h \
		../../Qt-Static/include/QtCore/qcompilerdetection.h \
		../../Qt-Static/include/QtCore/qtypeinfo.h \
		../../Qt-Static/include/QtCore/qtypetraits.h \
		../../Qt-Static/include/QtCore/qsysinfo.h \
		../../Qt-Static/include/QtCore/qlogging.h \
		../../Qt-Static/include/QtCore/qflags.h \
		../../Qt-Static/include/QtCore/qatomic.h \
		../../Qt-Static/include/QtCore/qbasicatomic.h \
		../../Qt-Static/include/QtCore/qatomic_bootstrap.h \
		../../Qt-Static/include/QtCore/qgenericatomic.h \
		../../Qt-Static/include/QtCore/qatomic_msvc.h \
		../../Qt-Static/include/QtCore/qatomic_armv7.h \
		../../Qt-Static/include/QtCore/qatomic_armv6.h \
		../../Qt-Static/include/QtCore/qatomic_armv5.h \
		../../Qt-Static/include/QtCore/qatomic_ia64.h \
		../../Qt-Static/include/QtCore/qatomic_mips.h \
		../../Qt-Static/include/QtCore/qatomic_x86.h \
		../../Qt-Static/include/QtCore/qatomic_cxx11.h \
		../../Qt-Static/include/QtCore/qatomic_gcc.h \
		../../Qt-Static/include/QtCore/qatomic_unix.h \
		../../Qt-Static/include/QtCore/qglobalstatic.h \
		../../Qt-Static/include/QtCore/qmutex.h \
		../../Qt-Static/include/QtCore/qnumeric.h \
		../../Qt-Static/include/QtCore/qobjectdefs_impl.h \
		../../Qt-Static/include/QtCore/qstring.h \
		../../Qt-Static/include/QtCore/qchar.h \
		../../Qt-Static/include/QtCore/qbytearray.h \
		../../Qt-Static/include/QtCore/qrefcount.h \
		../../Qt-Static/include/QtCore/qarraydata.h \
		../../Qt-Static/include/QtCore/qstringbuilder.h \
		../../Qt-Static/include/QtCore/qlist.h \
		../../Qt-Static/include/QtCore/qalgorithms.h \
		../../Qt-Static/include/QtCore/qiterator.h \
		../../Qt-Static/include/QtCore/qcoreevent.h \
		../../Qt-Static/include/QtCore/qscopedpointer.h \
		../../Qt-Static/include/QtCore/qmetatype.h \
		../../Qt-Static/include/QtCore/qvarlengtharray.h \
		../../Qt-Static/include/QtCore/qcontainerfwd.h \
		../../Qt-Static/include/QtCore/qisenum.h \
		../../Qt-Static/include/QtCore/qobject_impl.h \
		../../Qt-Static/include/QtNetwork/qabstractsocket.h \
		../../Qt-Static/include/QtCore/qiodevice.h \
		../../Qt-Static/include/QtCore/qdebug.h \
		../../Qt-Static/include/QtCore/qhash.h \
		../../Qt-Static/include/QtCore/qpair.h \
		../../Qt-Static/include/QtCore/qmap.h \
		../../Qt-Static/include/QtCore/qtextstream.h \
		../../Qt-Static/include/QtCore/qlocale.h \
		../../Qt-Static/include/QtCore/qvariant.h \
		../../Qt-Static/include/QtCore/qstringlist.h \
		../../Qt-Static/include/QtCore/qdatastream.h \
		../../Qt-Static/include/QtCore/qregexp.h \
		../../Qt-Static/include/QtCore/qstringmatcher.h \
		../../Qt-Static/include/QtCore/qshareddata.h \
		../../Qt-Static/include/QtCore/qvector.h \
		../../Qt-Static/include/QtCore/qpoint.h \
		../../Qt-Static/include/QtCore/qset.h \
		../../Qt-Static/include/QtCore/qcontiguouscache.h \
		../../Qt-Static/include/QtNetwork/qhostaddress.h \
		mythread.h \
		../../Qt-Static/include/QtCore/QThread \
		../../Qt-Static/include/QtCore/qthread.h \
		../../Qt-Static/include/QtNetwork/QTcpSocket \
		../../Qt-Static/include/QtNetwork/qtcpsocket.h \
		../../Qt-Static/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myserver.o myserver.cpp

mythread.o: mythread.cpp mythread.h \
		../../Qt-Static/include/QtCore/QThread \
		../../Qt-Static/include/QtCore/qthread.h \
		../../Qt-Static/include/QtCore/qobject.h \
		../../Qt-Static/include/QtCore/qobjectdefs.h \
		../../Qt-Static/include/QtCore/qnamespace.h \
		../../Qt-Static/include/QtCore/qglobal.h \
		../../Qt-Static/include/QtCore/qconfig.h \
		../../Qt-Static/include/QtCore/qfeatures.h \
		../../Qt-Static/include/QtCore/qsystemdetection.h \
		../../Qt-Static/include/QtCore/qprocessordetection.h \
		../../Qt-Static/include/QtCore/qcompilerdetection.h \
		../../Qt-Static/include/QtCore/qtypeinfo.h \
		../../Qt-Static/include/QtCore/qtypetraits.h \
		../../Qt-Static/include/QtCore/qsysinfo.h \
		../../Qt-Static/include/QtCore/qlogging.h \
		../../Qt-Static/include/QtCore/qflags.h \
		../../Qt-Static/include/QtCore/qatomic.h \
		../../Qt-Static/include/QtCore/qbasicatomic.h \
		../../Qt-Static/include/QtCore/qatomic_bootstrap.h \
		../../Qt-Static/include/QtCore/qgenericatomic.h \
		../../Qt-Static/include/QtCore/qatomic_msvc.h \
		../../Qt-Static/include/QtCore/qatomic_armv7.h \
		../../Qt-Static/include/QtCore/qatomic_armv6.h \
		../../Qt-Static/include/QtCore/qatomic_armv5.h \
		../../Qt-Static/include/QtCore/qatomic_ia64.h \
		../../Qt-Static/include/QtCore/qatomic_mips.h \
		../../Qt-Static/include/QtCore/qatomic_x86.h \
		../../Qt-Static/include/QtCore/qatomic_cxx11.h \
		../../Qt-Static/include/QtCore/qatomic_gcc.h \
		../../Qt-Static/include/QtCore/qatomic_unix.h \
		../../Qt-Static/include/QtCore/qglobalstatic.h \
		../../Qt-Static/include/QtCore/qmutex.h \
		../../Qt-Static/include/QtCore/qnumeric.h \
		../../Qt-Static/include/QtCore/qobjectdefs_impl.h \
		../../Qt-Static/include/QtCore/qstring.h \
		../../Qt-Static/include/QtCore/qchar.h \
		../../Qt-Static/include/QtCore/qbytearray.h \
		../../Qt-Static/include/QtCore/qrefcount.h \
		../../Qt-Static/include/QtCore/qarraydata.h \
		../../Qt-Static/include/QtCore/qstringbuilder.h \
		../../Qt-Static/include/QtCore/qlist.h \
		../../Qt-Static/include/QtCore/qalgorithms.h \
		../../Qt-Static/include/QtCore/qiterator.h \
		../../Qt-Static/include/QtCore/qcoreevent.h \
		../../Qt-Static/include/QtCore/qscopedpointer.h \
		../../Qt-Static/include/QtCore/qmetatype.h \
		../../Qt-Static/include/QtCore/qvarlengtharray.h \
		../../Qt-Static/include/QtCore/qcontainerfwd.h \
		../../Qt-Static/include/QtCore/qisenum.h \
		../../Qt-Static/include/QtCore/qobject_impl.h \
		../../Qt-Static/include/QtNetwork/QTcpSocket \
		../../Qt-Static/include/QtNetwork/qtcpsocket.h \
		../../Qt-Static/include/QtNetwork/qabstractsocket.h \
		../../Qt-Static/include/QtCore/qiodevice.h \
		../../Qt-Static/include/QtCore/qdebug.h \
		../../Qt-Static/include/QtCore/qhash.h \
		../../Qt-Static/include/QtCore/qpair.h \
		../../Qt-Static/include/QtCore/qmap.h \
		../../Qt-Static/include/QtCore/qtextstream.h \
		../../Qt-Static/include/QtCore/qlocale.h \
		../../Qt-Static/include/QtCore/qvariant.h \
		../../Qt-Static/include/QtCore/qstringlist.h \
		../../Qt-Static/include/QtCore/qdatastream.h \
		../../Qt-Static/include/QtCore/qregexp.h \
		../../Qt-Static/include/QtCore/qstringmatcher.h \
		../../Qt-Static/include/QtCore/qshareddata.h \
		../../Qt-Static/include/QtCore/qvector.h \
		../../Qt-Static/include/QtCore/qpoint.h \
		../../Qt-Static/include/QtCore/qset.h \
		../../Qt-Static/include/QtCore/qcontiguouscache.h \
		../../Qt-Static/include/QtCore/QDebug \
		../../Qt-Static/include/QtCore/QTextCodec \
		../../Qt-Static/include/QtCore/qtextcodec.h \
		../../Qt-Static/include/QtSql/QSqlDatabase \
		../../Qt-Static/include/QtSql/qsqldatabase.h \
		../../Qt-Static/include/QtSql/qsql.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mythread.o mythread.cpp

servergeomarketing_plugin_import.o: servergeomarketing_plugin_import.cpp ../../Qt-Static/include/QtCore/QtPlugin \
		../../Qt-Static/include/QtCore/qplugin.h \
		../../Qt-Static/include/QtCore/qobject.h \
		../../Qt-Static/include/QtCore/qobjectdefs.h \
		../../Qt-Static/include/QtCore/qnamespace.h \
		../../Qt-Static/include/QtCore/qglobal.h \
		../../Qt-Static/include/QtCore/qconfig.h \
		../../Qt-Static/include/QtCore/qfeatures.h \
		../../Qt-Static/include/QtCore/qsystemdetection.h \
		../../Qt-Static/include/QtCore/qprocessordetection.h \
		../../Qt-Static/include/QtCore/qcompilerdetection.h \
		../../Qt-Static/include/QtCore/qtypeinfo.h \
		../../Qt-Static/include/QtCore/qtypetraits.h \
		../../Qt-Static/include/QtCore/qsysinfo.h \
		../../Qt-Static/include/QtCore/qlogging.h \
		../../Qt-Static/include/QtCore/qflags.h \
		../../Qt-Static/include/QtCore/qatomic.h \
		../../Qt-Static/include/QtCore/qbasicatomic.h \
		../../Qt-Static/include/QtCore/qatomic_bootstrap.h \
		../../Qt-Static/include/QtCore/qgenericatomic.h \
		../../Qt-Static/include/QtCore/qatomic_msvc.h \
		../../Qt-Static/include/QtCore/qatomic_armv7.h \
		../../Qt-Static/include/QtCore/qatomic_armv6.h \
		../../Qt-Static/include/QtCore/qatomic_armv5.h \
		../../Qt-Static/include/QtCore/qatomic_ia64.h \
		../../Qt-Static/include/QtCore/qatomic_mips.h \
		../../Qt-Static/include/QtCore/qatomic_x86.h \
		../../Qt-Static/include/QtCore/qatomic_cxx11.h \
		../../Qt-Static/include/QtCore/qatomic_gcc.h \
		../../Qt-Static/include/QtCore/qatomic_unix.h \
		../../Qt-Static/include/QtCore/qglobalstatic.h \
		../../Qt-Static/include/QtCore/qmutex.h \
		../../Qt-Static/include/QtCore/qnumeric.h \
		../../Qt-Static/include/QtCore/qobjectdefs_impl.h \
		../../Qt-Static/include/QtCore/qstring.h \
		../../Qt-Static/include/QtCore/qchar.h \
		../../Qt-Static/include/QtCore/qbytearray.h \
		../../Qt-Static/include/QtCore/qrefcount.h \
		../../Qt-Static/include/QtCore/qarraydata.h \
		../../Qt-Static/include/QtCore/qstringbuilder.h \
		../../Qt-Static/include/QtCore/qlist.h \
		../../Qt-Static/include/QtCore/qalgorithms.h \
		../../Qt-Static/include/QtCore/qiterator.h \
		../../Qt-Static/include/QtCore/qcoreevent.h \
		../../Qt-Static/include/QtCore/qscopedpointer.h \
		../../Qt-Static/include/QtCore/qmetatype.h \
		../../Qt-Static/include/QtCore/qvarlengtharray.h \
		../../Qt-Static/include/QtCore/qcontainerfwd.h \
		../../Qt-Static/include/QtCore/qisenum.h \
		../../Qt-Static/include/QtCore/qobject_impl.h \
		../../Qt-Static/include/QtCore/qpointer.h \
		../../Qt-Static/include/QtCore/qsharedpointer.h \
		../../Qt-Static/include/QtCore/qshareddata.h \
		../../Qt-Static/include/QtCore/qsharedpointer_impl.h \
		../../Qt-Static/include/QtCore/qhash.h \
		../../Qt-Static/include/QtCore/qpair.h \
		../../Qt-Static/include/QtCore/qjsonobject.h \
		../../Qt-Static/include/QtCore/qjsonvalue.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o servergeomarketing_plugin_import.o servergeomarketing_plugin_import.cpp

moc_myserver.o: moc_myserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myserver.o moc_myserver.cpp

moc_mythread.o: moc_mythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mythread.o moc_mythread.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

